version: 2.1

orbs: 
  node: circleci/node@5.0.2

jobs:
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Linters
          command: yarn run lint

workflows:
  linter:
    jobs:
      - lint
